-- Fix: whoop_tokens.user_id needs UNIQUE constraint for ON CONFLICT(user_id) to work.
-- The unique index was already created in 002_recovery_mode.sql.
-- In PostgreSQL we don't need to recreate the table — the index is sufficient.
-- This migration is now a no-op since idx_whoop_tokens_user already exists.
